# Generated by Django 3.2.7 on 2022-06-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220613_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='filter_f',
            field=models.CharField(max_length=550),
        ),
    ]
